### ISSUE TITLE
failed to find tunnels

### ISSUE THREAD

**Issue by camjenk** [Storj/farmer-gui#205]
Just updated from 0.6.0 to 0.7.0

Filled in the data for the drives (screen shotted the old gui with the GB amounts and paths to be sure everything is exact)

using Win10
When i try to farm I get this error. Please help?
EDIT: Switched back to the older version for now and it works, hoping for news of a fix on the newer version.

### Drive1

```
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
node created with nodeID 475f51bf883d0fef058de44a9fdab831646bf0bd
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
publishing message on topic "0e01"
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
subscribing to topic "0e01"
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
subscribing to topic "0e00"
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
requesting probe from nearest neighbor
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
sending PROBE message to {"protocol":"0.6.0","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461699172703}
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
successfully traversed NAT via UPnP
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
subscribing to topic "0f01020202"
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
subscribing to topic "0f02020202"
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
subscribing to topic "0f03020202"
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
sending FIND_NODE message to {"protocol":"0.6.0","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461699174561}
{warn} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
rpc call 158123869f78d5a56e68c3c52594e38034c2d380 timed out
{info} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
requesting tunnelers from nearest neighbor
{info} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
sending FIND_TUNNEL message to {"protocol":"0.6.0","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461699192710}
{warn} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
rpc call 3121c269be18070b5149a85b4cbee09b5df00a2a timed out
{warn} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
query failed, removing contact for shortlist, reason RPC with ID `3121c269be18070b5149a85b4cbee09b5df00a2a` timed out
{warn} [Tue Apr 26 2016 14:33:26 GMT-0500 (Central Daylight Time)]
missing or empty reply from contact
{warn} [Tue Apr 26 2016 14:33:26 GMT-0500 (Central Daylight Time)]
missing or empty reply from contact
{warn} [Tue Apr 26 2016 14:33:26 GMT-0500 (Central Daylight Time)]
missing or empty reply from contact
{warn} [Tue Apr 26 2016 14:33:32 GMT-0500 (Central Daylight Time)]
rpc call 5ca621a8c15327d41357f336a4e3bdb74110cb1b timed out
{error} [Tue Apr 26 2016 14:33:32 GMT-0500 (Central Daylight Time)]
failed to find tunnels, reason: RPC with ID `5ca621a8c15327d41357f336a4e3bdb74110cb1b` timed out
```

### Drive 2

```
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
node created with nodeID a445c882d1f1e3930651b2d3c7351474ea5ce260
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
publishing message on topic "0e01"
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
subscribing to topic "0e01"
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
subscribing to topic "0e00"
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
requesting probe from nearest neighbor
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
sending PROBE message to {"protocol":"0.6.0","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461699172732}
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
successfully traversed NAT via UPnP
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
subscribing to topic "0f01020202"
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
subscribing to topic "0f02020202"
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
subscribing to topic "0f03020202"
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
sending FIND_NODE message to {"protocol":"0.6.0","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461699174614}
{warn} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
rpc call 258e254df4762fb2e830b6f6d053eeff838850e9 timed out
{info} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
requesting tunnelers from nearest neighbor
{info} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
sending FIND_TUNNEL message to {"protocol":"0.6.0","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461699192773}
{warn} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
rpc call e188f0d744b6df9686ab5b58125ad3366d007414 timed out
{warn} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
query failed, removing contact for shortlist, reason RPC with ID `e188f0d744b6df9686ab5b58125ad3366d007414` timed out
{warn} [Tue Apr 26 2016 14:33:26 GMT-0500 (Central Daylight Time)]
missing or empty reply from contact
{warn} [Tue Apr 26 2016 14:33:26 GMT-0500 (Central Daylight Time)]
missing or empty reply from contact
{warn} [Tue Apr 26 2016 14:33:26 GMT-0500 (Central Daylight Time)]
missing or empty reply from contact
{warn} [Tue Apr 26 2016 14:33:32 GMT-0500 (Central Daylight Time)]
rpc call d77ba4233ad9390d294cd91de3aefd1c40186be2 timed out
{error} [Tue Apr 26 2016 14:33:32 GMT-0500 (Central Daylight Time)]
failed to find tunnels, reason: RPC with ID `d77ba4233ad9390d294cd91de3aefd1c40186be2` timed out
```

### Drive 3

```
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
node created with nodeID 21baa00afb370e764124a7ee4c116c326634a405
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
publishing message on topic "0e01"
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
subscribing to topic "0e01"
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
subscribing to topic "0e00"
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
requesting probe from nearest neighbor
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
sending PROBE message to {"protocol":"0.6.0","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461699172760}
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
successfully traversed NAT via UPnP
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
subscribing to topic "0f01020202"
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
subscribing to topic "0f02020202"
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
subscribing to topic "0f03020202"
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
sending FIND_NODE message to {"protocol":"0.6.0","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461699174638}
{warn} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
rpc call e34c859279e12cc053b9359b0b26711ca3dab2d5 timed out
{info} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
requesting tunnelers from nearest neighbor
{info} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
sending FIND_TUNNEL message to {"protocol":"0.6.0","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461699192788}
{warn} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
rpc call 2cc81ab63dd2ed2a5d5dff3322dd46612f66e2e8 timed out
{warn} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
query failed, removing contact for shortlist, reason RPC with ID `2cc81ab63dd2ed2a5d5dff3322dd46612f66e2e8` timed out
{warn} [Tue Apr 26 2016 14:33:26 GMT-0500 (Central Daylight Time)]
missing or empty reply from contact
{warn} [Tue Apr 26 2016 14:33:26 GMT-0500 (Central Daylight Time)]
missing or empty reply from contact
{warn} [Tue Apr 26 2016 14:33:26 GMT-0500 (Central Daylight Time)]
missing or empty reply from contact
{warn} [Tue Apr 26 2016 14:33:32 GMT-0500 (Central Daylight Time)]
rpc call 7ad91712c1fd0943aff0b038ac9224cde8669fa1 timed out
{error} [Tue Apr 26 2016 14:33:32 GMT-0500 (Central Daylight Time)]
failed to find tunnels, reason: RPC with ID `7ad91712c1fd0943aff0b038ac9224cde8669fa1` timed out
```

### Drive 4

```
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
node created with nodeID 25f274cbbd326a4eeabe856477122bda1ad2bce4
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
publishing message on topic "0e01"
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
subscribing to topic "0e01"
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
subscribing to topic "0e00"
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
requesting probe from nearest neighbor
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
sending PROBE message to {"protocol":"0.6.0","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461699172785}
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
successfully traversed NAT via UPnP
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
subscribing to topic "0f01020202"
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
subscribing to topic "0f02020202"
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
subscribing to topic "0f03020202"
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
sending FIND_NODE message to {"protocol":"0.6.0","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461699174656}
{warn} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
rpc call 62d18f0ae8b9fba90092cc3323ce8540d7452556 timed out
{info} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
requesting tunnelers from nearest neighbor
{info} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
sending FIND_TUNNEL message to {"protocol":"0.6.0","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461699192804}
{warn} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
rpc call 70fcbbf9bd56fdb1cfaba680c4673d93df2b82b3 timed out
{warn} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
query failed, removing contact for shortlist, reason RPC with ID `70fcbbf9bd56fdb1cfaba680c4673d93df2b82b3` timed out
{warn} [Tue Apr 26 2016 14:33:26 GMT-0500 (Central Daylight Time)]
missing or empty reply from contact
{warn} [Tue Apr 26 2016 14:33:26 GMT-0500 (Central Daylight Time)]
missing or empty reply from contact
{warn} [Tue Apr 26 2016 14:33:26 GMT-0500 (Central Daylight Time)]
missing or empty reply from contact
{warn} [Tue Apr 26 2016 14:33:32 GMT-0500 (Central Daylight Time)]
rpc call ee723aef71edab0c6626cfa06d144269323ca125 timed out
{error} [Tue Apr 26 2016 14:33:32 GMT-0500 (Central Daylight Time)]
failed to find tunnels, reason: RPC with ID `ee723aef71edab0c6626cfa06d144269323ca125` timed out
```

### Drive 5

```
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
node created with nodeID db8c426e16eec77093b326124964405652d8f034
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
publishing message on topic "0e01"
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
subscribing to topic "0e01"
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
subscribing to topic "0e00"
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
requesting probe from nearest neighbor
{info} [Tue Apr 26 2016 14:32:52 GMT-0500 (Central Daylight Time)]
sending PROBE message to {"protocol":"0.6.0","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461699172810}
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
successfully traversed NAT via UPnP
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
subscribing to topic "0f01020202"
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
subscribing to topic "0f02020202"
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
subscribing to topic "0f03020202"
{info} [Tue Apr 26 2016 14:32:54 GMT-0500 (Central Daylight Time)]
sending FIND_NODE message to {"protocol":"0.6.0","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461699174586}
{warn} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
rpc call 4f07e72a526814cf404c0b4843a372d10429c736 timed out
{info} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
requesting tunnelers from nearest neighbor
{info} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
sending FIND_TUNNEL message to {"protocol":"0.6.0","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461699192819}
{warn} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
rpc call 45cdb3a06645e2dbe267e3d4eb972e88b1e26c5e timed out
{warn} [Tue Apr 26 2016 14:33:12 GMT-0500 (Central Daylight Time)]
query failed, removing contact for shortlist, reason RPC with ID `45cdb3a06645e2dbe267e3d4eb972e88b1e26c5e` timed out
{warn} [Tue Apr 26 2016 14:33:26 GMT-0500 (Central Daylight Time)]
missing or empty reply from contact
{warn} [Tue Apr 26 2016 14:33:26 GMT-0500 (Central Daylight Time)]
missing or empty reply from contact
{warn} [Tue Apr 26 2016 14:33:26 GMT-0500 (Central Daylight Time)]
missing or empty reply from contact
{warn} [Tue Apr 26 2016 14:33:32 GMT-0500 (Central Daylight Time)]
rpc call 3c52bf2692f69f80e9351c91a0cc04f07f70816c timed out
{error} [Tue Apr 26 2016 14:33:32 GMT-0500 (Central Daylight Time)]
failed to find tunnels, reason: RPC with ID `3c52bf2692f69f80e9351c91a0cc04f07f70816c` timed out
```

**Comment by gordonwritescode** [comment]
This should be resolved with tomorrow's deployment and today's releases.

**Comment by holyboly321** [comment]
I also had this problem with 0.7.0. 

I updated to 0.7.1, now i get the same error, but in a pop-up window.

My setup:
Windows 2012R2
No upnp, with NAT behind cisco firewall. (no ports forwarded)

**Comment by littleskunk** [comment]
Please try again after bridge update. You get the error message because we had 2 problems.
1.) UPNP doesn't work. Most of the farmer are unable to open tunnel ports for you. Hopefully solved with the new version but you have to wait until other farmer did the update. Your own update doesn't help you.
2.) Bridge was full of tunnel connection and didn't point you to other farmer that would allow you a tunnel connection. Hopefully solved with the bridge update comming today.

**Comment by littleskunk** [comment]
Number 1 is not solved. See https://github.com/Storj/farmer/issues/23

Anyway the bridge update can still fix it. Blackduck and I got some open tunnel ports for you all.

**Comment by camjenk** [comment]
Thanks for the help, I will keep the old client running until I see a working update. To get the new update do I simply open version 0.7.0 and accept a prompt?

**Comment by smilesvua** [comment]
Storj Share 0.7.2, problem exists.
`{info} [Fri Apr 29 2016 13:11:03 GMT+0300 (EEST)]
node created with nodeID 059e68178d3c4d2ebaea088f0ca6481dbf879155
{info} [Fri Apr 29 2016 13:11:03 GMT+0300 (EEST)]
publishing message on topic "0e01"
{info} [Fri Apr 29 2016 13:11:03 GMT+0300 (EEST)]
subscribing to topic "0e01"
{info} [Fri Apr 29 2016 13:11:03 GMT+0300 (EEST)]
subscribing to topic "0e00"
{info} [Fri Apr 29 2016 13:11:03 GMT+0300 (EEST)]
requesting probe from nearest neighbor
{info} [Fri Apr 29 2016 13:11:03 GMT+0300 (EEST)]
sending PROBE message to {"protocol":"0.6.5","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461924663323}
{warn} [Fri Apr 29 2016 13:11:03 GMT+0300 (EEST)]
could not connect to NAT device via UPnP
{info} [Fri Apr 29 2016 13:11:03 GMT+0300 (EEST)]
subscribing to topic "0f01020202"
{info} [Fri Apr 29 2016 13:11:03 GMT+0300 (EEST)]
subscribing to topic "0f02020202"
{info} [Fri Apr 29 2016 13:11:03 GMT+0300 (EEST)]
subscribing to topic "0f03020202"
{info} [Fri Apr 29 2016 13:11:03 GMT+0300 (EEST)]
sending FIND_NODE message to {"protocol":"0.6.5","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461924663468}
{info} [Fri Apr 29 2016 13:11:03 GMT+0300 (EEST)]
received valid message from {"protocol":"0.6.5","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461924663882}
{info} [Fri Apr 29 2016 13:11:03 GMT+0300 (EEST)]
requesting tunnelers from nearest neighbor
{info} [Fri Apr 29 2016 13:11:03 GMT+0300 (EEST)]
sending FIND_TUNNEL message to {"protocol":"0.6.5","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461924663916}
{info} [Fri Apr 29 2016 13:11:03 GMT+0300 (EEST)]
received valid message from {"protocol":"0.6.5","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461924663966}
{info} [Fri Apr 29 2016 13:11:04 GMT+0300 (EEST)]
sending FIND_NODE message to {"protocol":"0.6.5","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461924664000}
{info} [Fri Apr 29 2016 13:11:04 GMT+0300 (EEST)]
received valid message from {"protocol":"0.6.5","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461924664363}
{info} [Fri Apr 29 2016 13:11:04 GMT+0300 (EEST)]
sending OPEN_TUNNEL message to {"protocol":"0.6.5","address":"server012.storj.dk","port":5012,"nodeID":"ffa9832be51582d4a64bd3b60fb8c6347346ab79","lastSeen":1461924664391}
{info} [Fri Apr 29 2016 13:11:04 GMT+0300 (EEST)]
received valid message from {"protocol":"0.6.5","address":"api.storj.io","port":8443,"nodeID":"593844dc7f0076a1aeda9a6b9788af17e67c1052","lastSeen":1461924664434}
{warn} [Fri Apr 29 2016 13:11:04 GMT+0300 (EEST)]
missing or empty reply from contact
{warn} [Fri Apr 29 2016 13:11:23 GMT+0300 (EEST)]
rpc call 82fb9ba02d89ac6a3fc3f5a6218403a7ca1ba82c timed out
{info} [Fri Apr 29 2016 13:11:23 GMT+0300 (EEST)]
sending OPEN_TUNNEL message to {"protocol":"0.6.5","address":"server012.storj.dk","port":5012,"nodeID":"ffa9832be51582d4a64bd3b60fb8c6347346ab79","lastSeen":1461924683313}
{warn} [Fri Apr 29 2016 13:11:23 GMT+0300 (EEST)]`

**Comment by littleskunk** [comment]
And I have unused tunnels. My log:
```
{"level":"info","message":"publishing message on topic \"0e01\"","timestamp":"2016-04-29T09:53:01.397Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.6.5\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1461923581398}","timestamp":"2016-04-29T09:53:01.398Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.6.5\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1461923581730}","timestamp":"2016-04-29T09:53:01.730Z"}
{"level":"info","message":"publishing message on topic \"0e01\"","timestamp":"2016-04-29T10:08:01.480Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.6.5\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1461924481480}","timestamp":"2016-04-29T10:08:01.480Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.6.5\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1461924482316}","timestamp":"2016-04-29T10:08:02.316Z"}
```

**Comment by gordonwritescode** [comment]
This should be resolved by https://github.com/Storj/core/releases/tag/v0.6.6 and related releases.

**Comment by littleskunk** [comment]
My node has 2 open tunnel connection now.
```
{"level":"info","message":"received valid message from {\"protocol\":\"0.6.7\",\"address\":\"server023.storj.dk\",\"port\":28260,\"nodeID\":\"8147c13a37bddd5aeb84a2e32b49ffa942c6ca1d\",\"lastSeen\":1461987216560}","timestamp":"2016-04-30T03:33:36.560Z"}
{"level":"info","message":"opening gateway for 8147c13a37bddd5aeb84a2e32b49ffa942c6ca1d","timestamp":"2016-04-30T03:33:36.716Z"}
{"level":"info","message":"publishing message on topic \"0e00\"","timestamp":"2016-04-30T03:33:36.829Z"}
{"level":"info","message":"sending PUBLISH message to {\"protocol\":\"0.6.7\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1461987216830}","timestamp":"2016-04-30T03:33:36.830Z"}
{"level":"info","message":"gateway opened for 8147c13a37bddd5aeb84a2e32b49ffa942c6ca1d at {\"address\":\"<myddns>\",\"port\":4004}","timestamp":"2016-04-30T03:33:37.015Z"}
```

**Comment by pvdl** [comment]
I got also this issue:
Upgraded from 0.6 to .0.7.4
Storj Share Version 0.7.4 
Protocol Version 0.6.7
Linux Mint 17.3

{warn} [Tue May 03 2016 20:22:40 GMT+0200 (CEST)]
could not connect to NAT device via UPnP
...
{warn} [Tue May 03 2016 20:22:58 GMT+0200 (CEST)]
rpc call d54b8240a1d10e881a5f8787869fb3ee7c87e728 timed out
All other {info} messages seems ok.

Does Storj need a UPnP connection from outside to my computer?
